<?php

    $title = 'Envoyer un message';
    $this->headTitle($title);
    ?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php
    $form->setAttribute('action', $this->url('livre', array('action' => 'add')));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id_message'));
    echo $this->formRow($form->get('contenu'));
    echo '<br>';
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();