<?php

$title = 'Supprimer un message';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Êtes-vous sûr de vouloir supprimer ce message du livre d'or ?
    '<?php echo $this->escapeHtml($livre->contenu); ?>' (posté le 
    '<?php echo $this->escapeHtml($livre->date_message); ?>'?
</p>
<?php
$url = $this->url('livre', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $livre->id_message; ?>" />
    <input type="submit" name="del" value="Oui" />
    <input type="submit" name="del" value="Non" />
</div>
</form>