<?php

$title = 'Éditer ce message';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'livre',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id_message'));
echo $this->formRow($form->get('contenu'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();